# Generated by Django 5.0.4 on 2024-05-17 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Фамилия'),
        ),
    ]
