# Generated by Django 5.0.4 on 2024-05-18 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Фамилия')),
                ('password', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='Пароль')),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
