# Generated by Django 5.0.4 on 2024-05-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user1_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
    ]
