# Generated by Django 5.0.6 on 2024-06-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_menu_price_alter_menu_image_alter_menu_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
