# Generated by Django 5.0.6 on 2024-06-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_menu_options_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Категория'),
        ),
    ]
