# Generated by Django 5.0.6 on 2024-08-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_category_remove_menu_category_menu_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listPerson', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
