# Generated by Django 5.0.6 on 2024-08-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reserved/image', verbose_name='Изображение')),
            ],
        ),
    ]
