# Generated by Django 5.0.6 on 2024-08-02 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0004_cart_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(null=True, verbose_name='Количество')),
                ('summa', models.PositiveIntegerField(null=True, verbose_name='Сумма заказа')),
                ('taking_summa', models.CharField(default=0, max_length=10, verbose_name='Сумма доставки')),
                ('create_order', models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')),
                ('ending_order', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа')),
                ('status_order', models.CharField(choices=[('Создан', 'Создан'), ('В обработке', 'В обработке'), ('Готов', 'Готов'), ('Выполнен', 'Выполнен'), ('Отменен', 'Отменен')], default='Создан', max_length=100, verbose_name='Статус заказа')),
                ('is_payment', models.BooleanField(default=False, verbose_name='Оплата')),
                ('cart', models.ManyToManyField(to='shop.cart', verbose_name='Корзина для заказа')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
